project:
  type: website

website:
  title: "Historical databases at Virginia Tech"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    fontsize: 1.3rem

execute:
  freeze: true
  echo: false
  eval: true
  warning: false
  message: false

